bootstrapping

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
data = pd.read_csv('diabetes.csv')
df = pd.DataFrame(data)


In [9]:
subset = df.sample(n=100)

In [10]:
subset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
718            1      108             60             46      178  35.5   
483            0       84             82             31      125  38.2   
410            6      102             90             39        0  35.7   
425            4      184             78             39      277  37.0   
55             1       73             50             10        0  23.0   
..           ...      ...            ...            ...      ...   ...   
206            8      196             76             29      280  37.5   
446            1      100             72             12       70  25.3   
616            6      117             96              0        0  28.7   
510           12       84             72             31        0  29.7   
116            5      124             74              0        0  34.0   

     DiabetesPedigreeFunction  Age  Outcome  
718                     0.415   24        0  
483                     0.233   23        0  
410                     0.674   28        0  
425                     0.264   31        1  
55                      0.248   21        0  
..                        ...  ...      ...  
206                     0.605   57        1  
446                     0.658   28        0  
616                     0.157   30        0  
510                     0.297   46        1  
116                     0.220   38        1  

[100 rows x 9 columns]

In [11]:
x = subset.iloc[:,:-1].values
y = subset.iloc[:, -1].values

In [12]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,:-1])
x[:,:-1] = imputer.transform(x[:,:-1])

In [13]:
print(x)

[[1.000e+00 1.080e+02 6.000e+01 4.600e+01 1.780e+02 3.550e+01 4.150e-01
  2.400e+01]
 [0.000e+00 8.400e+01 8.200e+01 3.100e+01 1.250e+02 3.820e+01 2.330e-01
  2.300e+01]
 [6.000e+00 1.020e+02 9.000e+01 3.900e+01 0.000e+00 3.570e+01 6.740e-01
  2.800e+01]
 [4.000e+00 1.840e+02 7.800e+01 3.900e+01 2.770e+02 3.700e+01 2.640e-01
  3.100e+01]
 [1.000e+00 7.300e+01 5.000e+01 1.000e+01 0.000e+00 2.300e+01 2.480e-01
  2.100e+01]
 [1.000e+00 1.090e+02 3.800e+01 1.800e+01 1.200e+02 2.310e+01 4.070e-01
  2.600e+01]
 [2.000e+00 1.550e+02 5.200e+01 2.700e+01 5.400e+02 3.870e+01 2.400e-01
  2.500e+01]
 [0.000e+00 1.090e+02 8.800e+01 3.000e+01 0.000e+00 3.250e+01 8.550e-01
  3.800e+01]
 [7.000e+00 1.250e+02 8.600e+01 0.000e+00 0.000e+00 3.760e+01 3.040e-01
  5.100e+01]
 [1.000e+01 1.390e+02 8.000e+01 0.000e+00 0.000e+00 2.710e+01 1.441e+00
  5.700e+01]
 [4.000e+00 1.290e+02 6.000e+01 1.200e+01 2.310e+02 2.750e+01 5.270e-01
  3.100e+01]
 [0.000e+00 1.040e+02 6.400e+01 2.300e+01 1.160e+02 2.780e+01 4.5

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [15]:
print(x)

[[ 0.     1.     0.    ... 35.5    0.415 24.   ]
 [ 1.     0.     0.    ... 38.2    0.233 23.   ]
 [ 0.     0.     0.    ... 35.7    0.674 28.   ]
 ...
 [ 0.     0.     0.    ... 28.7    0.157 30.   ]
 [ 0.     0.     0.    ... 29.7    0.297 46.   ]
 [ 0.     0.     0.    ... 34.     0.22  38.   ]]


In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [17]:
print(y)

[0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 1
 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 0
 1 0 0 0 1 1 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1]


In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [19]:
print(x_train)

[[ 0.     0.     0.    ... 35.7    0.674 28.   ]
 [ 0.     0.     1.    ... 31.6    0.649 23.   ]
 [ 0.     0.     0.    ... 28.7    0.157 30.   ]
 ...
 [ 0.     0.     0.    ... 34.     0.43  43.   ]
 [ 1.     0.     0.    ... 43.5    0.347 21.   ]
 [ 0.     0.     0.    ... 30.2    0.364 24.   ]]


In [20]:
print(x_test)

[[0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
  1.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.10e+02 7.60e+01
  0.00e+00 0.00e+00 2.78e+01 2.37e-01 5.80e+01]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
  0.00e+00 1.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.12e+02 8.20e+01
  3.20e+01 1.75e+02 3.42e+01 2.60e-01 3.60e+01]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.00e+00 0.00e+00
  0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 8.70e+01 8.00e+01
  0.00e+00 0.00e+00 2.32e+01 8.40e-02 3.20e+01]
 [0.00e+00 0.00e+00 0.00e+00 1.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
  0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.00e+02 6.80e+01
  2.30e+01 8.10e+01 3.16e+01 9.49e-01 2.80e+01]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.00e+00
  0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.50e+02 7.80e+01
  2.90e+01 1.26e+02 3.52e+01 6.92e-01 5.40e+01]
 [0.00e+00 0.00e+00 

In [21]:
print(y_train)

[0 0 0 1 1 0 0 0 0 0 0 1 0 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1
 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1
 0 0 0 0 0 0]


In [22]:
print(y_test)

[0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0]


In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [24]:
print(x_train)

[[-0.2847474  -0.48038446 -0.37796447 ...  0.42341392  0.59575849
  -0.43407662]
 [-0.2847474  -0.48038446  2.64575131 ... -0.07777614  0.52973183
  -0.88742035]
 [-0.2847474  -0.48038446 -0.37796447 ... -0.43227643 -0.76967269
  -0.25273913]
 ...
 [-0.2847474  -0.48038446 -0.37796447 ...  0.21560341 -0.04866164
   0.92595457]
 [ 3.51188458 -0.48038446 -0.37796447 ...  1.37689744 -0.26787013
  -1.06875785]
 [-0.2847474  -0.48038446 -0.37796447 ... -0.24891421 -0.22297201
  -0.79675161]]


In [25]:
print(x_test)

[[-2.84747399e-01 -4.80384461e-01 -3.77964473e-01 -4.40488196e-01
  -2.84747399e-01 -3.33333333e-01 -2.84747399e-01 -1.12508790e-01
   5.06622805e+00 -1.97385508e-01 -1.97385508e-01 -1.12508790e-01
  -2.29415734e-01 -1.12508790e-01 -2.98586485e-01  2.69971710e-01
  -1.40714989e+00 -6.76659965e-01 -5.42293756e-01 -5.58387402e-01
   2.28598576e+00]
 [-2.84747399e-01 -4.80384461e-01 -3.77964473e-01 -4.40488196e-01
  -2.84747399e-01 -3.33333333e-01 -2.84747399e-01 -1.12508790e-01
  -1.97385508e-01  5.06622805e+00 -1.97385508e-01 -1.12508790e-01
  -2.29415734e-01 -1.12508790e-01 -2.37494621e-01  5.77777936e-01
   7.65530279e-01  5.92530752e-01  2.40051702e-01 -4.97642881e-01
   2.91273347e-01]
 [-2.84747399e-01 -4.80384461e-01 -3.77964473e-01 -4.40488196e-01
  -2.84747399e-01 -3.33333333e-01  3.51188458e+00 -1.12508790e-01
  -1.97385508e-01 -1.97385508e-01 -1.97385508e-01 -1.12508790e-01
  -2.29415734e-01 -1.12508790e-01 -1.00114292e+00  4.75175861e-01
  -1.40714989e+00 -6.76659965e-01 -1.1

In [26]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [27]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]]


In [28]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.6

In [29]:
subset_2 = df.sample(n= 400)

In [30]:
subset_2

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
640            0      102             86             17      105  29.3   
613            6      105             80             28        0  32.5   
415            3      173             84             33      474  35.7   
517            7      125             86              0        0  37.6   
195            5      158             84             41      210  39.4   
..           ...      ...            ...            ...      ...   ...   
94             2      142             82             18       64  24.7   
739            1      102             74              0        0  39.5   
81             2       74              0              0        0   0.0   
396            3       96             56             34      115  24.7   
580            0      151             90             46        0  42.1   

     DiabetesPedigreeFunction  Age  Outcome  
640                     0.695   27        0  
613                     0.878   26        0  
415                     0.258   22        1  
517                     0.304   51        0  
195                     0.395   29        1  
..                        ...  ...      ...  
94                      0.761   21        0  
739                     0.293   42        1  
81                      0.102   22        0  
396                     0.944   39        0  
580                     0.371   21        1  

[400 rows x 9 columns]

In [31]:
x = subset.iloc[:,:-1].values
y = subset.iloc[:, -1].values

In [32]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,:-1])
x[:,:-1] = imputer.transform(x[:,:-1])

In [33]:
print(x)

[[1.000e+00 1.080e+02 6.000e+01 4.600e+01 1.780e+02 3.550e+01 4.150e-01
  2.400e+01]
 [0.000e+00 8.400e+01 8.200e+01 3.100e+01 1.250e+02 3.820e+01 2.330e-01
  2.300e+01]
 [6.000e+00 1.020e+02 9.000e+01 3.900e+01 0.000e+00 3.570e+01 6.740e-01
  2.800e+01]
 [4.000e+00 1.840e+02 7.800e+01 3.900e+01 2.770e+02 3.700e+01 2.640e-01
  3.100e+01]
 [1.000e+00 7.300e+01 5.000e+01 1.000e+01 0.000e+00 2.300e+01 2.480e-01
  2.100e+01]
 [1.000e+00 1.090e+02 3.800e+01 1.800e+01 1.200e+02 2.310e+01 4.070e-01
  2.600e+01]
 [2.000e+00 1.550e+02 5.200e+01 2.700e+01 5.400e+02 3.870e+01 2.400e-01
  2.500e+01]
 [0.000e+00 1.090e+02 8.800e+01 3.000e+01 0.000e+00 3.250e+01 8.550e-01
  3.800e+01]
 [7.000e+00 1.250e+02 8.600e+01 0.000e+00 0.000e+00 3.760e+01 3.040e-01
  5.100e+01]
 [1.000e+01 1.390e+02 8.000e+01 0.000e+00 0.000e+00 2.710e+01 1.441e+00
  5.700e+01]
 [4.000e+00 1.290e+02 6.000e+01 1.200e+01 2.310e+02 2.750e+01 5.270e-01
  3.100e+01]
 [0.000e+00 1.040e+02 6.400e+01 2.300e+01 1.160e+02 2.780e+01 4.5

In [34]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [35]:
print(x)

[[ 0.     1.     0.    ... 35.5    0.415 24.   ]
 [ 1.     0.     0.    ... 38.2    0.233 23.   ]
 [ 0.     0.     0.    ... 35.7    0.674 28.   ]
 ...
 [ 0.     0.     0.    ... 28.7    0.157 30.   ]
 [ 0.     0.     0.    ... 29.7    0.297 46.   ]
 [ 0.     0.     0.    ... 34.     0.22  38.   ]]


In [36]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [37]:
print(y)

[0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 1
 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 0
 1 0 0 0 1 1 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1]


In [38]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [39]:
print(x_train)

[[ 0.     0.     0.    ... 35.7    0.674 28.   ]
 [ 0.     0.     1.    ... 31.6    0.649 23.   ]
 [ 0.     0.     0.    ... 28.7    0.157 30.   ]
 ...
 [ 0.     0.     0.    ... 34.     0.43  43.   ]
 [ 1.     0.     0.    ... 43.5    0.347 21.   ]
 [ 0.     0.     0.    ... 30.2    0.364 24.   ]]


In [40]:
print(x_test)

[[0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
  1.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.10e+02 7.60e+01
  0.00e+00 0.00e+00 2.78e+01 2.37e-01 5.80e+01]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
  0.00e+00 1.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.12e+02 8.20e+01
  3.20e+01 1.75e+02 3.42e+01 2.60e-01 3.60e+01]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.00e+00 0.00e+00
  0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 8.70e+01 8.00e+01
  0.00e+00 0.00e+00 2.32e+01 8.40e-02 3.20e+01]
 [0.00e+00 0.00e+00 0.00e+00 1.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
  0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.00e+02 6.80e+01
  2.30e+01 8.10e+01 3.16e+01 9.49e-01 2.80e+01]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.00e+00
  0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.50e+02 7.80e+01
  2.90e+01 1.26e+02 3.52e+01 6.92e-01 5.40e+01]
 [0.00e+00 0.00e+00 

In [41]:
print(y_train)

[0 0 0 1 1 0 0 0 0 0 0 1 0 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1
 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1
 0 0 0 0 0 0]


In [42]:
print(y_test)

[0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0]


In [43]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [44]:
print(x_train)

[[-0.2847474  -0.48038446 -0.37796447 ...  0.42341392  0.59575849
  -0.43407662]
 [-0.2847474  -0.48038446  2.64575131 ... -0.07777614  0.52973183
  -0.88742035]
 [-0.2847474  -0.48038446 -0.37796447 ... -0.43227643 -0.76967269
  -0.25273913]
 ...
 [-0.2847474  -0.48038446 -0.37796447 ...  0.21560341 -0.04866164
   0.92595457]
 [ 3.51188458 -0.48038446 -0.37796447 ...  1.37689744 -0.26787013
  -1.06875785]
 [-0.2847474  -0.48038446 -0.37796447 ... -0.24891421 -0.22297201
  -0.79675161]]


In [45]:
print(x_test)

[[-2.84747399e-01 -4.80384461e-01 -3.77964473e-01 -4.40488196e-01
  -2.84747399e-01 -3.33333333e-01 -2.84747399e-01 -1.12508790e-01
   5.06622805e+00 -1.97385508e-01 -1.97385508e-01 -1.12508790e-01
  -2.29415734e-01 -1.12508790e-01 -2.98586485e-01  2.69971710e-01
  -1.40714989e+00 -6.76659965e-01 -5.42293756e-01 -5.58387402e-01
   2.28598576e+00]
 [-2.84747399e-01 -4.80384461e-01 -3.77964473e-01 -4.40488196e-01
  -2.84747399e-01 -3.33333333e-01 -2.84747399e-01 -1.12508790e-01
  -1.97385508e-01  5.06622805e+00 -1.97385508e-01 -1.12508790e-01
  -2.29415734e-01 -1.12508790e-01 -2.37494621e-01  5.77777936e-01
   7.65530279e-01  5.92530752e-01  2.40051702e-01 -4.97642881e-01
   2.91273347e-01]
 [-2.84747399e-01 -4.80384461e-01 -3.77964473e-01 -4.40488196e-01
  -2.84747399e-01 -3.33333333e-01  3.51188458e+00 -1.12508790e-01
  -1.97385508e-01 -1.97385508e-01 -1.97385508e-01 -1.12508790e-01
  -2.29415734e-01 -1.12508790e-01 -1.00114292e+00  4.75175861e-01
  -1.40714989e+00 -6.76659965e-01 -1.1

In [46]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [47]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]]


In [48]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.6